everted ------------------------------------------------------------------------ r30561 | etxrab | 2009-10-15 18:57:26 +0200 (Do, 15 Okt 2009) | 1 line
gtk_option_menu -> gtk_combo_box
------------------------------------------------------------------------

as it broke compilation on my system and I don't know enough about gtk
to fix it properly.


In file included from /usr/include/gtk-2.0/gtk/gtk.h:224,
                 from /home/jmayer/work/wireshark/svn/trunk/gtk/scsi_stat.c:35:
/usr/include/gtk-2.0/gtk/gtkitemfactory.h:47: warning: function declaration isn’t a prototype
/home/jmayer/work/wireshark/svn/trunk/gtk/scsi_stat.c: In function ‘scsistat_program_select’:
/home/jmayer/work/wireshark/svn/trunk/gtk/scsi_stat.c:122: error: ‘SCSI_STAT_PROG_LABEL_SBC’ undeclared (first use in this function)
/home/jmayer/work/wireshark/svn/trunk/gtk/scsi_stat.c:122: error: (Each undeclared identifier is reported only once
/home/jmayer/work/wireshark/svn/trunk/gtk/scsi_stat.c:122: error: for each function it appears in.)
/home/jmayer/work/wireshark/svn/trunk/gtk/scsi_stat.c:125: error: ‘SCSI_STAT_PROG_LABEL_SSC’ undeclared (first use in this function)
/home/jmayer/work/wireshark/svn/trunk/gtk/scsi_stat.c:128: error: ‘SCSI_STAT_PROG_LABEL_MMC’ undeclared (first use in this function)
/home/jmayer/work/wireshark/svn/trunk/gtk/scsi_stat.c:129: error: ‘SCSI_DEV_MMC’ undeclared (first use in this function)
/home/jmayer/work/wireshark/svn/trunk/gtk/scsi_stat.c: In function ‘gtk_scsistat_init’:
/home/jmayer/work/wireshark/svn/trunk/gtk/scsi_stat.c:229: warning: assignment discards qualifiers from pointer target type
/home/jmayer/work/wireshark/svn/trunk/gtk/scsi_stat.c:234: warning: assignment discards qualifiers from pointer target type
/home/jmayer/work/wireshark/svn/trunk/gtk/scsi_stat.c:239: warning: assignment discards qualifiers from pointer target type
/home/jmayer/work/wireshark/svn/trunk/gtk/scsi_stat.c:244: warning: assignment discards qualifiers from pointer target type
/home/jmayer/work/wireshark/svn/trunk/gtk/scsi_stat.c:249: warning: assignment discards qualifiers from pointer target type
/home/jmayer/work/wireshark/svn/trunk/gtk/scsi_stat.c: At top level:
/home/jmayer/work/wireshark/svn/trunk/gtk/scsi_stat.c:333: warning: comma at end of enumerator list
/home/jmayer/work/wireshark/svn/trunk/gtk/scsi_stat.c: In function ‘gtk_scsistat_cb’:
/home/jmayer/work/wireshark/svn/trunk/gtk/scsi_stat.c:388: error: ‘severity_combo_box’ undeclared (first use in this function)
/home/jmayer/work/wireshark/svn/trunk/gtk/scsi_stat.c:343: warning: unused variable ‘menu_item’
/home/jmayer/work/wireshark/svn/trunk/gtk/scsi_stat.c: At top level:
/home/jmayer/work/wireshark/svn/trunk/gtk/scsi_stat.c:452: warning: no previous declaration for ‘register_tap_listener_gtkscsistat’
make[2]: *** [gtk/CMakeFiles/ui.dir/scsi_stat.c.o] Error 1




git-svn-id: svn+ssh://svn.wireshark.org/svn/wireshark/trunk@30565 f5534014-38df-0310-8fa8-9805f1628bb7