Fix error when building QtShark:
...\capture_opts.h(94) : error C2461: 'remote_host' : constructor syntax missing formal parameters



git-svn-id: svn+ssh://svn.wireshark.org/svn/wireshark/trunk@40723 f5534014-38df-0310-8fa8-9805f1628bb7