Fix compilation error:
packet-amqp.c:5617:5: error: "/*" within comment

Cause:

Previous comment wasn't terminated right



git-svn-id: svn+ssh://svn.wireshark.org/svn/wireshark/trunk@36454 f5534014-38df-0310-8fa8-9805f1628bb7