Fix win* buildbot warnings: packet_panes.c(304) : error C2220: warning treated as error - no 'object' file generated packet_panes.c(304) : warning C4244: 'function' : conversion from 'gdouble' to 'int', possible loss of data packet_panes.c(304) : warning C4244: 'function' : conversion from 'gdouble' to 'int', possible loss of data
Add casts, old code did the same casts so this should be OK.


git-svn-id: svn+ssh://svn.wireshark.org/svn/wireshark/trunk@43730 f5534014-38df-0310-8fa8-9805f1628bb7